import io
from fpdf import FPDF
from datetime import datetime

class RoutePDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Route Planner Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_route_pdf(graph_image_io, route_details=None, map_image_base64=None):
    """
    Generates a PDF report containing route details, coordinates, and visual maps.
    graph_image_io: BytesIO of the internal graph.
    map_image_base64: Base64 string of the client-side Leaflet map.
    """
    pdf = RoutePDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Title / Metadata
    pdf.cell(0, 10, f"Generated by: {route_details.get('username', 'Unknown')}", 0, 1)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    
    if route_details:
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Route Metrics:", 0, 1)
        pdf.set_font("Arial", size=12)
        pdf.cell(0, 10, f"Total Distance: {route_details.get('distance', 0)} km", 0, 1)
        pdf.cell(0, 10, f"Estimated Time: {route_details.get('time', '?')}", 0, 1)
        
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Waypoints:", 0, 1)
        pdf.set_font("Arial", size=10)
        
        start_coords = route_details.get('start_coords', '')
        end_coords = route_details.get('end_coords', '')
        
        pdf.cell(0, 8, f"FROM: {route_details.get('start_name', '?')}", 0, 1)
        pdf.cell(0, 8, f"   Coords: {start_coords}", 0, 1)
        
        if route_details.get('mid_name'):
             mid_coords = route_details.get('mid_coords', '')
             pdf.cell(0, 8, f"VIA: {route_details.get('mid_name')}", 0, 1)
             pdf.cell(0, 8, f"   Coords: {mid_coords}", 0, 1)
             
        pdf.cell(0, 8, f"TO: {route_details.get('end_name', '?')}", 0, 1)
        pdf.cell(0, 8, f"   Coords: {end_coords}", 0, 1)
    
    import tempfile
    import os
    import base64

    # MAP SECTION (Leaflet)
    if map_image_base64:
        pdf.ln(5)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Interactive Map View (Leaflet):", 0, 1)
        
        # Decode base64
        try:
             # Remove header if present (e.g. "data:image/png;base64,")
             if ',' in map_image_base64:
                 map_image_base64 = map_image_base64.split(',')[1]
             
             map_bytes = base64.b64decode(map_image_base64)
             
             with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp_map:
                tmp_map.write(map_bytes)
                tmp_map_path = tmp_map.name
             
             pdf.image(tmp_map_path, x=10, y=None, w=190)
             os.unlink(tmp_map_path)
             pdf.ln(5)
        except Exception as e:
            pdf.cell(0, 10, f"Error including map image: {str(e)}", 0, 1)

    # GRAPH SECTION
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Internal Graph Logic:", 0, 1)
    
    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
        graph_image_io.seek(0)
        tmp.write(graph_image_io.read())
        tmp_path = tmp.name
    
    try:
        pdf.image(tmp_path, x=10, y=None, w=190)
    finally:
        os.unlink(tmp_path)
    
    pdf.ln(10)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 10, "This report was generated automatically by RoutePlanner.")

    # Return PDF as bytes
    # FPDF2 output() returns bytearray if no arguments are passed (since v2.5.0)
    try:
        pdf_bytes = pdf.output()
        return io.BytesIO(bytes(pdf_bytes))
    except TypeError:
         # Fallback for older versions or if it requires dest='S'
         # actually fpdf2 might need a dummy name sometimes or behave differently
         # Safer approach for some versions:
         return io.BytesIO(pdf.output(dest='S').encode('latin-1'))
